###########
# site.title

title:    'Malrio'
subtitle: 'Deep Learning AI + Map Generator for Super MarioÂ Playing in Minecraft'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
